name: Secret Rotation Schedule

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Branch
        run: |
          git checkout -b test-2
          git push --set-upstream origin test-2
          
