name: Secret Rotation Schedule

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Branch
        run: |
          git checkout -b test-2
          git push --set-upstream origin test-2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create PR when issues was created
        uses: chyccs/empty-pr-actions@master
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
