name: Secret Rotation Schedule

on:
  workflow_dispatch:

jobs:
  build_FEATURE_BRANCH:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Pull Request
      uses: backstage-test/create-pull-request@v6
