name: Secret Rotation Schedule

on:
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "app/backstage-actions"
          git config --local user.name "app/backstage-actions"
          git checkout -b $(date +secret-rotation-%d-%m-%Y)
          git commit --allow-empty -m "empty"
          git push --set-upstream origin $(date +secret-rotation-%d-%m-%Y)
          gh pr create -B main -H $(date +secret-rotation-%d-%m-%Y) --title $(date +%d-%m-%Y) 'PR for Secret Rotation' --body 'Created by Github action'
    
      - name: Sleep
        run: sleep 5s
        shell: bash
      
      - name: Create Branch
        run: |
          gh pr close $(date +secret-rotation-%d-%m-%Y) -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}         


