name: Secret Rotation Schedule

on:
  schedule:
    - cron:  '0 6 * * SAT'
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Create Branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "github-actions/backstage"
          git config --local user.name "github-actions/backstage"
          touch secret-rotation
          date=$(date '+%d-%m-%Y')
          echo $date >> secret-rotation
          git checkout -b $(date +secret-rotation-%d-%m-%Y)
          git add secret-rotation
          git commit -m "secret-rotation"
          git push --set-upstream origin $(date +secret-rotation-%d-%m-%Y)
          gh pr create -B main -H $(date +secret-rotation-%d-%m-%Y) --title 'PR for Secret Rotation' --body 'Created by Github action'
    
      - name: Sleep
        run: sleep 120s
        shell: bash
      
      - name: Create Branch
        run: |
          gh pr close $(date +secret-rotation-%d-%m-%Y) -d
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
