name: Secret Rotation Schedule

on:
  workflow_dispatch:

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create Pull Request
        id: testesttsetse
        uses: backstage-test/create-pull-request@v6
