name: Testing Vars

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  TestVars:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name:  Test
        run: |
          echo ${{ github.event.pull_request.head.ref || github.repository}}
